#Informacion del puerto en el que se deployará el servicio
server:
  port: ${PORT:0} 
  
#Informacion de la aplicacion, nombre con el que será registardo en el server eureka

spring:
  application:
    name: micro-servicio-uno
    
#Informacion del log

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.microservicios: 'DEBUG'
    
      

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
